---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-${ANIMALS}-deploy
  labels:
    app: stateful-${ANIMALS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful-${ANIMALS}
  template:
    metadata:
      labels:
        app: stateful-${ANIMALS}
    spec:
      containers:
      - name: api-${ANIMALS}
        image: nikigor/sre:3
        ports:
        - name: api-${ANIMALS}-port
          containerPort: 8081
        env:
        - name: DSN
          value: postgresql://myuser:mypassword@stateful-${ANIMALS}-svc:5432/mydb
        - name: ANIMALS
          value: ${ANIMALS}
        command: ["./api"]
      - name: db
        image: postgres:14-alpine
        env:
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DB
          value: mydb
        ports:
        - name: db-${ANIMALS}-port
          containerPort: 5432
        volumeMounts:
        - name: db-${ANIMALS}-data
          mountPath: /var/lib/postgresql/data
        - name: db-${ANIMALS}-init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-${ANIMALS}-data
          emptyDir: {}
        - name: db-${ANIMALS}-init-sql
          configMap:
            name: init-${ANIMALS}-sql

---
apiVersion: v1
kind: Service
metadata:
  name: stateful-${ANIMALS}-svc
spec:
  selector:
    app: stateful-${ANIMALS}
  ports:
  - name: api-${ANIMALS}-http
    port: 80
    targetPort: api-${ANIMALS}-port
  - name: db-${ANIMALS}-http
    port: 5432
    targetPort: db-${ANIMALS}-port

